/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ftec.exemplo.crud;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//br.com.ftec.exemplo.crud//CRUDExemplo//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "CRUDExemploTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "br.com.ftec.exemplo.crud.CRUDExemploTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CRUDExemploAction",
        preferredID = "CRUDExemploTopComponent")
@Messages({
    "CTL_CRUDExemploAction=CRUDExemplo",
    "CTL_CRUDExemploTopComponent=CRUDExemplo Window",
    "HINT_CRUDExemploTopComponent=This is a CRUDExemplo window"
})
public final class CRUDExemploTopComponent extends TopComponent {

    public CRUDExemploTopComponent() {
        initComponents();
        setName(Bundle.CTL_CRUDExemploTopComponent());
        setToolTipText(Bundle.HINT_CRUDExemploTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        exemploCRUD1 = new br.com.ftec.exemplo.crud.ExemploCRUD();

        jScrollPane1.setViewportView(exemploCRUD1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.ftec.exemplo.crud.ExemploCRUD exemploCRUD1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
